# Generated by Django 3.2.4 on 2021-06-24 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0004_auto_20210624_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 24, 9, 21, 11, 340709), null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='game_id',
            field=models.IntegerField(default=0),
        ),
    ]
