# Generated by Django 3.2.4 on 2021-06-23 07:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieweb', '0002_auto_20210622_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 23, 2, 34, 15, 413778), null=True),
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.BooleanField(default=True)),
                ('entity', models.TextField(max_length=200)),
                ('first', models.BooleanField(default=False)),
                ('last', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieweb.scoreboard')),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
