# Generated by Django 3.2.4 on 2021-06-24 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0003_auto_20210623_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 24, 1, 44, 45, 864556), null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='entity',
            field=models.IntegerField(default=0),
        ),
    ]
