# Generated by Django 3.2.4 on 2021-06-24 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0006_auto_20210624_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 24, 13, 45, 8, 530738), null=True),
        ),
    ]
