# Generated by Django 3.2.4 on 2021-07-06 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0009_auto_20210702_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='tmdbID',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdbID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 6, 10, 9, 5, 26209), null=True),
        ),
    ]
