# Generated by Django 3.2.5 on 2021-07-13 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0011_auto_20210709_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 11, 50, 10, 703908), null=True),
        ),
    ]
