# Generated by Django 3.2.5 on 2021-07-13 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0012_alter_scoreboard_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favAct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playersFA', to='movieweb.actor'),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 13, 16, 53, 0, 545657), null=True),
        ),
    ]
