# Generated by Django 3.2.5 on 2021-07-16 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0013_auto_20210713_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='actsDisc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='alwaysEndAct',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='alwaysEndMov',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favAct',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favMov',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favRol',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favStart',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='movsDisc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rolsDisc',
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 15, 19, 28, 11, 908431), null=True),
        ),
    ]
