# Generated by Django 3.2.5 on 2021-10-05 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0016_alter_scoreboard_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favAct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playersFA', to='movieweb.actor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favMov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playersFM', to='movieweb.movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favStart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playersFS', to='movieweb.turn'),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 3, 17, 16, 192850), null=True),
        ),
    ]
