# Generated by Django 3.2.5 on 2021-10-05 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0017_auto_20211005_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 7, 32, 27, 51797), null=True),
        ),
    ]
