# Generated by Django 3.2.5 on 2021-10-05 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0018_alter_scoreboard_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 7, 49, 16, 197127), null=True),
        ),
    ]
