# Generated by Django 3.2.5 on 2021-10-05 08:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieweb', '0019_alter_scoreboard_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favStart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playersFS', to='movieweb.actor'),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 8, 15, 33, 741146), null=True),
        ),
    ]
